gems:
- jekyll-gallery-generator
- jekyll-redirect-from

url: http://damgargroup.com.au
# baseurl: "/"
# url: http://localhost:3000

name: Damgar Property Group
brand: Damgar Property Group
description: Damgar Property Group is at the forefront of small to medium residential and commercial property development in inner Melbourne.
keyword: property developer, builder, construction

email: admin@damgargroup.com.au
phone: 03 9596 8543â€¨
# Keep address to one line if you want to use maps (for URL ecaping)
address: 79 Asling St, Brighton VIC 3186

author: Nathan Birrell

analytics: UA-81747047-1
year: 2016
markdown: kramdown
exclude:
  - node_modules

permalink: pretty

gallery:
  dir: project-photos       # Path to the gallery
  title: "Project Photos"   # Title for gallery index page
  sort_field: "title"       # How to sort galleries on the index page.
  scale_method: fill
  thumbnail_size:
    x: 1080                 # max width of thumbnails (in pixels)
    y: 600                  # max height of thumbnails (in pixels)

latest_project_url: 'http://google.com.au'
